<%@ Page Language="C#" AutoEventWireup="true" CodeFile="htmlexcel.aspx.cs" Inherits="htmlexcel" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    <div id="dvInfo" runat="server">
    <br />
            <center>
                <b>Student Informations Generated By CODE SCRATCHER</b></center>
                <br />
            <table align='center' border='1' bordercolor='#00aeef' width='50%' class='reporttable1'
                cellspacing='0' cellpadding='0' style='font-size: 10;'>
                <tr align='center'>
                    <td style='width: 10%'>
                        <b>RollNo</b>
                    </td>
                    <td>
                        <b>Name</b>
                    </td>
                    <td>
                        <b>College Name</b>
                    </td>
                </tr>
                <tr>
                    <td>
                        A1
                    </td>
                    <td>
                        Rahul
                    </td>
                    <td>
                        College of Eng
                    </td>
                </tr>
                <tr>
                    <td>
                        A2
                    </td>
                    <td>
                        Ramesh
                    </td>
                    <td>
                        College of IT
                    </td>
                </tr>
            </table>
            <br />
            <br />
        </div>
        <center>
            <asp:Button ID="Button2" runat="server" Style="height: 30px;" OnClick="Button2_Click"
                Text="Export HTML to Excel" />
        </center>
    </div>
    </form>
</body>
</html>
